2023-07-23 20:15:56.223641: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-07-23 20:15:56.223827: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
wandb: Currently logged in as: harrak-oussama2002. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in C:\Users\DELL\Downloads\FederatedLearning\OpenFL-extended\openfl-tutorials\boosting-examples\CoxPH\AdaBoostF_Support_Feature\workspace\wandb\run-20230723_201614-kvca2pn9
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vivid-lake-28
wandb:  View project at https://wandb.ai/harrak-oussama2002/Federated_Learning_support_feature
wandb:  View run at https://wandb.ai/harrak-oussama2002/Federated_Learning_support_feature/runs/kvca2pn9
{'aggregator': {'settings': {'assigner': 'openfl.component.assigner.AdaBoostAssigner', 'best_state_path': 'save/best.pbuf', 'db_store_rounds': 1, 'init_state_path': 'save/init.pbuf', 'last_state_path': 'save/last.pbuf', 'nn': False, 'rounds_to_train': 100, 'write_logs': False}, 'template': 'openfl.component.aggregator.Aggregator'}, 'api_layer': {'required_plugin_components': {'serializer_plugin': 'openfl.plugins.interface_serializer.dill_serializer.DillSerializer'}, 'settings': {'aggregation_function_interface_file': 'aggregation_function_obj.pkl', 'dataloader_interface_file': 'loader_obj.pkl', 'model_interface_file': 'model_obj.pkl', 'task_assigner_file': 'task_assigner_obj.pkl', 'tasks_interface_file': 'tasks_obj.pkl'}}, 'assigner': {'settings': {'task_groups': [{'name': 'train_and_validate', 'percentage': 1.0, 'tasks': ['1_train', '2_weak_learners_validate', '3_adaboost_update', '4_adaboost_validate']}]}, 'template': 'openfl.component.assigner.AdaBoostAssigner'}, 'collaborator': {'settings': {'db_store_rounds': 2, 'delta_updates': False, 'device_assignment_policy': 'CPU_ONLY', 'nn': False, 'opt_treatment': 'CONTINUE_GLOBAL'}, 'template': 'openfl.component.collaborator.Collaborator'}, 'compression_pipeline': {'settings': {'nn': False}, 'template': 'openfl.pipelines.GenericPipeline'}, 'network': {'settings': {'agg_addr': 'localhost', 'agg_port': 'auto', 'cert_folder': 'cert', 'client_reconnect_interval': 5, 'disable_client_auth': False, 'hash_salt': 'auto', 'tls': False}, 'template': 'openfl.federation.Network'}, 'task_runner': {'required_plugin_components': {'framework_adapters': 'openfl.plugins.frameworks_adapters.generic_adapter.GenericAdapter'}, 'settings': {}, 'template': 'openfl.federated.task.runner_generic.GenericTaskRunner'}, 'tasks': {'1_train': {'aggregation_type': 'openfl.interface.aggregation_functions.AggregateRandomForest', 'function': 'train_adaboost', 'kwargs': {'apply': 'global', 'data': 'train', 'retrieve': 'weak_learner'}}, '2_weak_learners_validate': {'aggregation_type': 'openfl.interface.aggregation_functions.AggregateAdaboost', 'function': 'validate_weak_learners', 'kwargs': {'apply': 'global', 'data': 'train', 'retrieve': 'model'}, 'n_classes': 2}, '3_adaboost_update': {'aggregation_type': 'openfl.interface.aggregation_functions.WeightedAverage', 'function': 'adaboost_update', 'kwargs': {'apply': 'global', 'retrieve': 'adaboost_coeff'}}, '4_adaboost_validate': {'aggregation_type': 'openfl.interface.aggregation_functions.WeightedAverage', 'function': 'validate_adaboost', 'kwargs': {'apply': 'local', 'data': 'test', 'retrieve': 'adaboost'}}, 'settings': {}}}
[20:16:15] INFO     Building [20:16:15] INFO     Building [20:16:15] INFO     Building [20:16:15] INFO     Building [20:16:15] INFO     Building [20:16:15] INFO     Building --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 170, in emit
    self.console.print(log_renderable)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 1720, in print
    self._buffer.extend(new_segments)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\redirect.py", line 640, in write
    self._old_write(data)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f846' in position 0: character maps to <undefined>
Call stack:
  File "AdaBoostF_Support_Feature.py", line 127, in <module>
    fl_experiment.start(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 234, in start
    self.prepare_workspace_distribution(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 177, in prepare_workspace_distribution
    self._serialize_interface_objects(model_provider, task_keeper, data_loader, task_assigner)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 434, in _serialize_interface_objects
    serializer = self.plan.build(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\federated\plan\plan.py", line 171, in build
    Plan.logger.info(f'Building [red]\U0001f846[/] Object [red]{class_name}[/] '
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 954, in handle
    self.emit(record)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 172, in emit
    self.handleError(record)
Message: 'Building [red]\U0001f846[/] Object [red]DillSerializer[/] from [red]openfl.plugins.interface_serializer.dill_serializer[/] Module.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 170, in emit
    self.console.print(log_renderable)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 1720, in print
    self._buffer.extend(new_segments)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\redirect.py", line 640, in write
    self._old_write(data)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f846' in position 0: character maps to <undefined>
Call stack:
  File "AdaBoostF_Support_Feature.py", line 127, in <module>
    fl_experiment.start(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 234, in start
    self.prepare_workspace_distribution(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 177, in prepare_workspace_distribution
    self._serialize_interface_objects(model_provider, task_keeper, data_loader, task_assigner)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 436, in _serialize_interface_objects
    framework_adapter = Plan.build(model_provider.framework_plugin, {})
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\federated\plan\plan.py", line 171, in build
    Plan.logger.info(f'Building [red]\U0001f846[/] Object [red]{class_name}[/] '
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 954, in handle
    self.emit(record)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 172, in emit
    self.handleError(record)
Message: 'Building [red]\U0001f846[/] Object [red]GenericAdapter[/] from [red]openfl.plugins.frameworks_adapters.generic_adapter[/] Module.'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 170, in emit
    self.console.print(log_renderable)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 1720, in print
    self._buffer.extend(new_segments)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
[20:16:15] INFO     Building [20:16:15] INFO     Building   File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\redirect.py", line 640, in write
    self._old_write(data)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f846' in position 0: character maps to <undefined>
Call stack:
  File "AdaBoostF_Support_Feature.py", line 127, in <module>
    fl_experiment.start(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 240, in start
    self.logger.info('Starting experiment!')
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 954, in handle
    self.emit(record)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 172, in emit
    self.handleError(record)
Message: 'Starting experiment!'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 170, in emit
    self.console.print(log_renderable)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 1720, in print
    self._buffer.extend(new_segments)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\redirect.py", line 640, in write
    self._old_write(data)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f846' in position 0: character maps to <undefined>
Call stack:
  File "AdaBoostF_Support_Feature.py", line 127, in <module>
    fl_experiment.start(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 241, in start
    self.plan.resolve()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\federated\plan\plan.py", line 242, in resolve
    self.federation_uuid = f'{self.name}_{self.hash[:8]}'
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\federated\plan\plan.py", line 235, in hash
    Plan.logger.info(f'FL-Plan hash is [blue]{self.hash_.hexdigest()}[/]',
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 954, in handle
    self.emit(record)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 172, in emit
    self.handleError(record)
Message: 'FL-Plan hash is [blue]b3a3507103d6ab2384292d1489f3f2880501b0a8de404eae1b53062689019a971567a2548df5c97c8178358be77d5195[/]'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 170, in emit
    self.console.print(log_renderable)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 1720, in print
    self._buffer.extend(new_segments)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\redirect.py", line 640, in write
    self._old_write(data)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f846' in position 0: character maps to <undefined>
Call stack:
  File "AdaBoostF_Support_Feature.py", line 127, in <module>
    fl_experiment.start(
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\interface\interactive_api\experiment.py", line 241, in start
    self.plan.resolve()
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\federated\plan\plan.py", line 253, in resolve
    self.hash[:8], 16
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\openfl\federated\plan\plan.py", line 235, in hash
    Plan.logger.info(f'FL-Plan hash is [blue]{self.hash_.hexdigest()}[/]',
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\Users\DELL\anaconda3\envs\myenv\lib\logging\__init__.py", line 954, in handle
    self.emit(record)
  File "C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\rich\logging.py", line 172, in emit
    self.handleError(record)
Message: 'FL-Plan hash is [blue]b3a3507103d6ab2384292d1489f3f2880501b0a8de404eae1b53062689019a971567a2548df5c97c8178358be77d5195[/]'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
[20:16:15] INFO     Building forrtl: error (200): program aborting due to window-CLOSE event
Image              PC                Routine            Line        Source             
libifcoremd.dll    00007FFE7DD2DF54  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFED7682943  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFED8787614  Unknown               Unknown  Unknown
ntdll.dll          00007FFED98E26F1  Unknown               Unknown  Unknown
2023-07-23 20:31:29.072509: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-07-23 20:31:29.072656: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
forrtl: error (200): program aborting due to window-CLOSE event
Image              PC                Routine            Line        Source             
libifcoremd.dll    00007FFE7D66DF54  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFED7682943  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFED8787614  Unknown               Unknown  Unknown
ntdll.dll          00007FFED98E26F1  Unknown               Unknown  Unknown
